### ISSUE TITLE
.purs file compiled, but not watched

### ISSUE THREAD

**Issue by adamw** [ethul/purescript-webpack-example#1]
When running `webpack-dev-server` or `webpack --watch`, recompilation is triggered only for `.purs` files which are included from javascript sources. E.g. if I have in javascript the following:

```
import main from './src/Main.purs';
```

Then any change to `Main.purs` will trigger recompilation. But if a `.purs` file is not imported from JS, it's not being watched (however it's included in compilation, when compilation is triggered).

**Comment by ethul** [comment]
Thanks for reporting. Is it possible to see your webpack config?

Also, what version of the purs-loader and purescript-webpack-plugin are you using?

**Comment by adamw** [comment]
Sure, here's my webpack config:

```
var path = require('path');

// https://github.com/ethul/purescript-webpack-example
var PurescriptWebpackPlugin = require('purescript-webpack-plugin');

var purescriptWebpackPlugin = new PurescriptWebpackPlugin({
  src: ['bower_components/purescript-*/src/**/*.purs', 'src/**/*.purs'],
  psc: 'psa',
  pscArgs: {
    sourceMaps: true
  }
});

module.exports = {
  entry: "./app.js",
  output: {
    filename: "bundle.js"
  },
  module: {
    loaders: [
      {
        test: /\.js$/,
        exclude: /node_modules|bower_components/,
        loader: 'babel-loader',
        query: {
          cacheDirectory: true, 
          presets: ['es2015'] 
        }
      },
      {
        test: /\.purs$/,
        loader: 'purs-loader'
      }
    ]
  },
  // http://stackoverflow.com/questions/30870830/how-do-i-generate-sourcemaps-when-using-babel-and-webpack
  devtool: 'source-map',
  resolve: {
    modulesDirectories: ['node_modules', 'bower_components'],
    extensions: [ '', '.js', '.purs']
  },
  plugins: [ purescriptWebpackPlugin ]
};
```

I have the latest versions of both I believe, from `package.json`:

```
    "purescript-webpack-plugin": "^0.2.0",
    "purs-loader": "^0.6.0",
```

**Comment by ethul** [comment]
Thanks for the configuration file. The setup looks okay to me.

If you were to clone the `purescript-webpack-example`, do you encounter the same problem?

**Comment by adamw** [comment]
I'm not sure why or how, but it just works today ... sorry for wasting your time :)

**Comment by ethul** [comment]
Glad it is working!

**Comment by adamw** [comment]
Ok, I wasn't going crazy ;) So I think the problem is when `webpack -w` is started when a compilation error exists. Here are the steps to reproduce:

* edit a `.purs` file, I tried with `src/Example/Bar.purs`, `src/Example/Foo/Boz.purs` and `src/Example/Test.purs`, change `String` to `Int` or anything else that will cause compilation to fail
* run `webpack -w`
* you should see the compilation error
* now fix the error & save the file. Compilation isn't triggered.

**Comment by ethul** [comment]
Thank you for following up on this and the detailed rundown to reproduce the issue. I agree this is a problem. I think it is related to:

ethul/purescript-webpack-plugin#24

**Comment by adamw** [comment]
Could be, however I can see the error - not sure if it hangs later, or just doesn't detect changes, though :)

**Comment by ethul** [comment]
Okay. Noted. Thanks!

**Comment by ethul** [comment]
Now that we just use the `purs-loader`, is this still an issue?

**Comment by ethul** [comment]
Closing. Please reopen at on the purs-loader repository if this issue crops up again.

**Comment by adamw** [comment]
Sorry for the late response, just noticed this :) I updated my `package.json`, now it only contains `purs-loader`. My `webpack.config.js` also looks similar to what's here. But still, if there's an error in a file on startup, no changes are detected. Everything works fine if the initial compilation passes without errors.

**Comment by ethul** [comment]
Thanks for the update. I've opened this at ethul/purs-loader#73

**Comment by ethul** [comment]
I've published a beta release that should fix  this issue. If you are willing to give it a try, that would be great! You can install the release under the `beta` dist tag.

```
npm install purs-loader@beta
```

In this release, there is a new option called `watch`. Please set this to true in your webpack config if you are running webpack in watch mode.

Thanks!
