### ISSUE TITLE
Update resolve.extensions

### ISSUE THREAD

**Issue by ethul** [ethul/purescript-webpack-example#3]
Include a recommendation to set `config.resolve.extensions = [ '', '.purs']`. When both `.js` and `.purs` are included, requiring a PureScript file without the `.purs` extension will default to it's corresponding FFI file if one exists.

Another possibility is to reorder the extensions to be `config.resolve.extensions = [ '', '.purs', '.js']`. Try this out to see if webpack will prefer the `.purs` over the `.js` for a file with the same name.

**Comment by irium** [comment]
`config.resolve.extensions = [ '', '.purs', '.js', '.jsx']` works for me like a charm :)

**Comment by ethul** [comment]
Thanks for confirming. I've updated the config to `[ '', '.purs', '.js']`
