### ISSUE TITLE
Use with source map loader

### ISSUE THREAD

**Issue by nwolverson** [ethul/purescript-webpack-example#4]
A previous version of this repo had a setup with source maps, I know the purs-loader went through some changes since then. I tried to enable source maps and set the right devtool/use source-map-loader as before but that didn't seem to work.

Do you know if it's possible to do this still or is there some blocker?

**Comment by ethul** [comment]
I admit I haven't tried this with the `source-map-loader` in a while, but I believe it should still work. One thing I can think of is to double check that `pscArgs: { sourceMaps: true }` is set as an option to the `purs-loader`. If you are able to provide your webpack config, I can dig into this a bit more.

**Comment by ethul** [comment]
Closing. Please open on ethul/purs-loader if there is still an issue with this. Thanks!

**Comment by nwolverson** [comment]
For the record I can't say one way or the other if there's any issue, I moved onto other things before getting anywhere, I've certainly lost all state by this point...

**Comment by ethul** [comment]
Thanks for the update.

**Comment by paulyoung** [comment]
I tried to get this working in this repo in a similar fashion to what was done in https://github.com/ethul/purescript-webpack-example/commit/14df7ec233fe7cb197c25bc01be7c135abc53726 but haven't been able to get source maps working that way yet.

**Comment by paulyoung** [comment]
Correction: https://github.com/ethul/purescript-webpack-example/commit/a015281de1251d067cec3df9c333613701820374

**Comment by paulyoung** [comment]
Some debug info:

```sh
DEBUG='purs-loader' npm run webpack:server

> purescript-webpack-example@0.1.0 webpack:server /Users/py/projects/ethul/purescript-webpack-example
> webpack-dev-server --progress --inline --hot

 10% building modules 1/1 modules 0 active
Project is running at http://localhost:4008/
webpack output is served from /
Content not from webpack is served from .
 10% building modules 4/9 modules 5 active ...bpack-example/node_modules/url/url.js  purs-loader loading Example +0ms
  purs-loader compile psa [ '--output=output',
  purs-loader   '--source-maps',
  purs-loader   'bower_components/purescript-*/src/**/*.purs',
  purs-loader   'src/**/*.purs' ] +1ms
  purs-loader compiling PureScript... +3ms
  ...
```

**Comment by paulyoung** [comment]
FWIW, I see this:

![screen shot 2017-08-01 at 4 59 54 pm](https://user-images.githubusercontent.com/84700/28851976-ddf8f33c-76da-11e7-8bd7-abc308762e14.png)

**Comment by ethul** [comment]
Thanks for the information and following up on this. I will take a look at the example to see if we can get source maps going. In case it is an issue, I've opened up ethul/purs-loader#101

**Comment by ethul** [comment]
I've added source map support in the loader with version `3.1.0`. The `source-map-loader` is not required for source map support. I have an example branch:

https://github.com/ethul/purescript-webpack-example/tree/source-maps

If anyone has a chance to give it a try, that would be great!

Closing this for now. We can reopen if there are more issues with source maps.

**Comment by paulyoung** [comment]
This worked for me, although the source maps weren't as interactive as I'd hoped. Thanks!

**Comment by nwolverson** [comment]
@paulyoung What do you mean interactive? If you can identify specific deficiencies it's probably something that needs to be fixed upstream in the compiler, but won't happen without such input

**Comment by paulyoung** [comment]
@nwolverson I meant that I wasn't able to hover over names of things and see their values, like I can when debugging JavaScript.

It also didn't seem possible to set a "nested" breakpoint like I can in JavaScript, which is useful for curried functions.

**Comment by paulyoung** [comment]
I've just come across some "nested" breakpoints, so not sure what changed there.

**Comment by paulyoung** [comment]
I am able to hover over things but the tooltips all show "ReferenceError: x is not defined"

**Comment by paulyoung** [comment]
Actually, some things that are in scope have information equivalent to debugging in JS.
