### ISSUE TITLE
main entry point

### ISSUE THREAD

**Issue by voland62** [ethul/purescript-webpack-example#7]
Hi there. I tried to test purs-loader, and add this file to src(imports are dropped for concise):
`
main :: forall e. Eff (console :: CONSOLE | e) Unit

main = do
        log "Hello purs-loader!"
`
Than I added new entry point to webpack.cofing.js
"purescript-test": [
            './src/Main.purs']
which outpus to purescript-test-bundle.js,
and created new purescript-test.html file with <script	src="/static/purescript-test-bundle.js"></script>
   Browser sees the code, and I expect some output in console, of course, but I don't see it.
When I add some code with unsafePerformEff - I see result, and this is what makes me confused. I guess that I need to do some setting to force purs produce main entry point: like -m Main --main Main. But I'm not sure how to do this via purs-loader config....

**Comment by ethul** [comment]
Thanks for the report. We currently have a PR open on this ethul/purs-loader#72. There are still some ideas to work out, but contributions are welcome on this if you're interested.

**Comment by voland62** [comment]
Thanks for reply.
Just for now, I accepted something like [that](https://github.com/bodil/purescript-webapp/blob/master/test/entry.js)

**Comment by ethul** [comment]
Welcome.

Closing. See ethul/purs-loader#72
