### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by voland62** [ethul/purescript-webpack-example#8]
Could it be updated to the latest purs setup? It mostly works with 0.11.7 + psc-package, but I can't get it working in fast-rebuild settings - hot reload doesn't reload .purs modules (.js modules does).

Thx.

**Comment by ethul** [comment]
Thanks for bringing this up. I may have a chance over the next few days to do the update.

**Comment by ethul** [comment]
I've updated the fast-rebuild and psc-package branches. I didn't notice any issue with the hot reloading. If you have a specific problem, please open a separate issue detailing it.

Thanks!

**Comment by vyorkin** [comment]
I've just tried it (fast-rebuild branch) and it does a _full page reload_ instead of _hot reloading._
Maybe I'm missing smth.
Is [HMR](https://webpack.js.org/concepts/hot-module-replacement/) == "Hot reloading" ?

**Comment by ethul** [comment]
Good point. From what I understand webpack will first try to hot reload the
module and then fall back to reloading the entire page. In the docs, the
example shows adding the “HotModuleReplacementPlugin”. Would you be willing
to try adding this to see if it works?
